"""add billing period to invoices

Revision ID: 5a16998388c3
Revises: 3a3ee11a060b
Create Date: 2026-06-26 11:23:25.347355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a16998388c3'
down_revision: Union[str, Sequence[str], None] = '3a3ee11a060b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('billing_month', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('billing_year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'billing_year')
    op.drop_column('invoices', 'billing_month')
    # ### end Alembic commands ###
