"""create pricing tiers table

Revision ID: 82faddc6b5cd
Revises: d6525463eb59
Create Date: 2026-06-23 18:33:52.012519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82faddc6b5cd'
down_revision: Union[str, Sequence[str], None] = 'd6525463eb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_tiers',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('min_units', sa.Integer(), nullable=False),
    sa.Column('max_units', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_tiers')
    # ### end Alembic commands ###
