"""add customer to usage events

Revision ID: ff6ec099337b
Revises: b4f188dbcb22
Create Date: 2026-06-30 17:00:16.151227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6ec099337b'
down_revision: Union[str, Sequence[str], None] = 'b4f188dbcb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    op.add_column(
        "usage_events",
        sa.Column(
            "customer_id",
            sa.UUID(),
            nullable=True
        )
    )

    op.create_foreign_key(
        None,
        "usage_events",
        "customers",
        ["customer_id"],
        ["id"]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_events', type_='foreignkey')
    op.drop_column('usage_events', 'customer_id')
    op.drop_constraint(None, 'customers', type_='unique')
    op.create_unique_constraint(op.f('uq_customer_external_id_per_org'), 'customers', ['organization_id', 'external_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
